// Code generated by sqlc. DO NOT EDIT.

package minesweeper

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateGame(ctx context.Context, arg CreateGameParams) (Game, error)
	GetAccountByID(ctx context.Context, id uuid.UUID) (Account, error)
	GetGameByID(ctx context.Context, id uuid.UUID) (Game, error)
	UpdateGame(ctx context.Context, arg UpdateGameParams) (Game, error)
}

var _ Querier = (*Queries)(nil)
